name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag git-lfs-server:latest
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}          
   
    -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tygozwolle/git-lfs-test-server:dev
          context: .
      #    cache-from: type=gha
       #   cache-to: type=gha,mode=max                  
